# Generated by Django 4.2 on 2023-04-13 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='context',
            new_name='content',
        ),
    ]
