# Generated by Django 4.2 on 2023-04-15 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myboard', '0002_rename_context_question_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
